aspnetmvcdapper/aspnetmvcdapper/Controllers/urunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using aspnetmvcdapper.Models;//EKLE
using Dapper;//EKLE
using System.Web.Mvc;

namespace aspnetmvcdapper.Controllers
{
    public class urunController : Controller
    {
        // GET: urun
        public ActionResult Index()
        {
            return View(DP.ReturnList<urunmodel>("urunlistele")); //listeleme işlemi musterimodel de kolonlarımız var
        }
        [HttpGet]
        public ActionResult ekle(int id = 0)
        {
            if (id == 0)
                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@urunid", id);

                return View(DP.ReturnList<urunmodel>("urunsirala", param).FirstOrDefault<urunmodel>());
            }
        }
        [HttpPost]
        public ActionResult ekle(urunmodel ekle)
        {
            //view oluştururken edit olanı seçiyoruz
            DynamicParameters param = new DynamicParameters();
            param.Add("@urunid", ekle.urunid);
            param.Add("@urunad", ekle.urunad);
            param.Add("@marka", ekle.marka);
            param.Add("@kategoriid", ekle.kategoriid);
            param.Add("@fiyat", ekle.fiyat);
            param.Add("@stok", ekle.stok);
            DP.ExecuteWithoutReturn("urunekle", param);
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("urunid", id);
            DP.ExecuteWithoutReturn("urunsilno", param);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvcdapper/aspnetmvcdapper/Views/urun/Index.cshtml
@model IEnumerable<aspnetmvcdapper.Models.urunmodel>
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

<p>
    @*@Html.ActionLink("Yeni Ürün Ekle", "ekle")*@ <!--link şeklinde -->
    <button type="button" class="btn btn-info" onclick="location.href = '@Url.Action("ekle","urun")'">Ürün Ekle</button><!--buton şeklinde -->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.urunad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.marka)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kategoriid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stok)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.urunad)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.marka)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.kategoriid)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.fiyat)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.stok)
    </td>
    <td>
        @*@Html.ActionLink("Düzenle", "ekle", new { id = item.urunid }) |
            @Html.ActionLink("Sil", "Delete", new { id = item.urunid })*@
        <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("ekle","urun",new { id = item.urunid })'">Düzenle</button>
        @*<button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("ekle","urun", new { id = item.urunid }))'">Sil</button>*@@*direk uyarı vermeden siler ve ındex sayfasına yönlendirir*@
        @Html.ActionLink("Sil", "Delete", new { id = item.urunid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İsteğinizden Emin Misiniz?')" }) @*1.parametre adı butonda gözükecek ad,2.parametre gideceği yer*@
    </td>
</tr>
    }

</table>

aspnetmvcdapper/aspnetmvcdapper/Views/urun/ekle.cshtml
@model aspnetmvcdapper.Models.urunmodel
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Ürün Ekle</h4>
    <hr />
    @Html.ValidationSummary(true) @*//ekledik, giden verilerin kontrolünü sağlar*@
    @Html.HiddenFor(model => model.urunid) @*//ekledik, id yi getirir*@
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.urunad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunad, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = 50 } }) @*required = "required", maxlength = 50 alanları il giriş zorunlu hale getirildi ve metin boyutusınırlandırıldı. *@
            @Html.ValidationMessageFor(model => model.urunad, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.marka, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.marka, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = 50 } })
            @Html.ValidationMessageFor(model => model.marka, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.kategoriid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.kategoriid, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.kategoriid, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fiyat, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.fiyat, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.stok, htmlAttributes: new { @class = "control-label col-md-2", required = "required" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stok, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stok, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />
            @*@Html.ActionLink("Geri Dön", "Index")*@ @*bu da çalışır ama buton özelliği vermek için aşağıdaki gibi yazılır*@
            <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index","urun")'">Geri Dön</button>
        </div>
    </div>
</div>
}


@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@
<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>