aspnetmvcdapper/aspnetmvcdapper/Controllers/satisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using aspnetmvcdapper.Models;//EKLE
using Dapper;//EKLE
using System.Web.Mvc;

namespace aspnetmvcdapper.Controllers
{
    public class satisController : Controller
    {
        // GET: satis
        public ActionResult Index()
        {
            return View(DP.ReturnList<satismodel>("satislistele")); //listeleme işlemi satismodel de kolonlarımız var
        }
        [HttpGet]
        public ActionResult ekle(int id = 0)
        {
            if (id == 0)
                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@satisid", id);

                return View(DP.ReturnList<satismodel>("satissirala", param).FirstOrDefault<satismodel>());
            }
        }
        [HttpPost]
        public ActionResult ekle(satismodel ekle)
        {
            //view oluştururken edit olanı seçiyoruz
            DynamicParameters param = new DynamicParameters();
            param.Add("@satisid", ekle.satisid);
            param.Add("@urunid", ekle.urunid);
            param.Add("@musteriid", ekle.musteriid);
            param.Add("@adet", ekle.adet);
            param.Add("@fiyat", ekle.fiyat);
            DP.ExecuteWithoutReturn("satisekle", param);
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("satisid", id);
            DP.ExecuteWithoutReturn("satissilno", param);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvcdapper/aspnetmvcdapper/Views/satis/Index.cshtml
@model IEnumerable<aspnetmvcdapper.Models.satismodel>
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

<p>
    @*@Html.ActionLink("Yeni Satış Ekle", "ekle")*@
    <button type="button" class="btn btn-info" onclick="location.href = '@Url.Action("ekle","satis")'">Satış Ekle</button><!--buton şeklinde -->
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.urunid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.musteriid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fiyat)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.urunid)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.musteriid)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.adet)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.fiyat)
    </td>

    <td>
        @*@Html.ActionLink("Düzenle", "ekle", new { id = item.satisid })*@ <!--ekle ve Delete Controllerdaki metotların adı,Düzenle ve Sil Labelda görünecek ad-->
        @*@Html.ActionLink("Sil", "Delete", new { id = item.satisid })*@

        <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("ekle","satis",new { id = item.satisid })'">Düzenle</button>
        @*<button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("ekle","satis", new { id = item.satisid }))'">Sil</button>*@@*direk uyarı vermeden siler ve Index sayfasına yönlendirir*@
        @Html.ActionLink("Sil", "Delete", new { id = item.satisid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İsteğinizden Emin Misiniz?')" }) @*1.parametre adı butonda gözükecek ad,2.parametre gideceği yer*@
    </td>
</tr>

    }

</table>

aspnetmvcdapper/aspnetmvcdapper/Views/satis/ekle.cshtml
@model aspnetmvcdapper.Models.satismodel
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Satış Ekle</h4>
        <hr />
        @Html.ValidationSummary(true) @*//ekledik,kontrolünü sağlar giden verilerin*@
        @Html.HiddenFor(model => model.satisid) @*//ekledik, id yi getirir*@
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.urunid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urunid, new { htmlAttributes = new { @class = "form-control", required = "required" } })@*required kısıtlaması getirildi *@
                @Html.ValidationMessageFor(model => model.urunid, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.musteriid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.musteriid, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.musteriid, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.adet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adet, new { htmlAttributes = new { @class = "form-control",required = "required" } })
                @Html.ValidationMessageFor(model => model.adet, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fiyat, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.fiyat, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
                @*@Html.ActionLink("Geri Dön", "Index")*@ @*bu da çalışır ama buton özelliği vermek için aşağıdaki gibi yazılır*@
                <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index","satis")'">Geri Dön</button>
            </div>
        </div>
    </div>
}

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@
<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>