aspnetmvcdapper/aspnetmvcdapper/Controllers/musteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using aspnetmvcdapper.Models;//EKLE
using Dapper;//EKLE
using System.Web.Mvc;

namespace aspnetmvcdapper.Controllers
{
    public class musteriController : Controller
    {
        // GET: musteri
        public ActionResult Index()
        {
            return View(DP.ReturnList<musterimodel>("musterilistele")); //listeleme işlemi musterimodel de kolonlarımız var
        }
        [HttpGet]
        public ActionResult ekle(int id = 0)
        {
            if (id == 0)
                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@musteriid", id);

                return View(DP.ReturnList<musterimodel>("musterisirala", param).FirstOrDefault<musterimodel>());
            }
        }
        [HttpPost]
        public ActionResult ekle(musterimodel ekle)
        {
            //view oluştururken edit olanı seçiyoruz
            DynamicParameters param = new DynamicParameters();
            param.Add("@musteriid", ekle.musteriid);
            param.Add("@musteriad", ekle.musteriad);
            param.Add("@musterisoyad", ekle.musterisoyad);
            DP.ExecuteWithoutReturn("musteriekle", param);
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("musteriid", id);
            DP.ExecuteWithoutReturn("musterisilno", param);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvcdapper/aspnetmvcdapper/Views/musteri/Index.cshtml
@model IEnumerable<aspnetmvcdapper.Models.musterimodel>
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

<p>
    @*@Html.ActionLink("Müşteri Ekle", "ekle")*@ <!--link şeklinde -->
    <button type="button" class="btn btn-info" onclick="location.href = '@Url.Action("ekle","musteri")'">Müşteri Ekle</button><!--buton şeklinde -->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.musteriad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.musterisoyad)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.musteriad)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.musterisoyad)
    </td>
    <td>
        @*@Html.ActionLink("Düzenle", "ekle", new { id = item.musteriid })*@
        @*@Html.ActionLink("Sil", "Delete", new { id = item.musteriid })*@
        <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("ekle","musteri",new { id = item.musteriid })'">Düzenle</button>
        @*<button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("ekle","musteri", new { id = item.musteriid }))'">Sil</button>*@@*direk uyarı vermeden siler ve ındex sayfasına yönlendirir*@
        @Html.ActionLink("Sil", "Delete", new { id = item.musteriid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İsteğinizden Emin Misiniz?')" }) @*1.parametre adı butonda gözükecek ad,2.parametre gideceği yer*@
    </td>
</tr>
    }

</table>

aspnetmvcdapper/aspnetmvcdapper/Views/musteri/ekle.cshtml
@model aspnetmvcdapper.Models.musterimodel
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Müşteri Ekle</h4>
        <hr />
        @Html.ValidationSummary(true) @*//ekledik,kontrolünü sağlar giden verilerin*@
        @Html.HiddenFor(model => model.musteriid) @*//ekledik, id yi getirir*@
        <hr />
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.musteriad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.musteriad, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = 50 } })@*required ve maxlength kısıtlamaları getirildi *@
                @Html.ValidationMessageFor(model => model.musteriad, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.musterisoyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.musterisoyad, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = 50 } })
                @Html.ValidationMessageFor(model => model.musterisoyad, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />

                @*@Html.ActionLink("Geri Dön", "Index")*@ @*bu da çalışır ama buton özelliği vermek için aşağıdaki gibi yazılır*@
                <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index","musteri")'">Geri Dön</button>
            </div>
        </div>
    </div>
}

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@
<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>