aspnetmvcdapper/aspnetmvcdapper/Controllers/kategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using aspnetmvcdapper.Models;//EKLE
using Dapper;//EKLE
using System.Web.Mvc;

namespace aspnetmvcdapper.Controllers
{
    public class kategoriController : Controller
    {
        // GET: kategori
        public ActionResult Index()
        {

            return View(DP.ReturnList<kategorimodel>("kategorilistele")); //listeleme işlemi kategorimodel de kolonlarımız var
        }
        [HttpGet]
        public ActionResult ekle(int id = 0)
        {
            if (id == 0)
                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@kategoriid", id);

                return View(DP.ReturnList<kategorimodel>("kategorisirala", param).FirstOrDefault<kategorimodel>());
            }
        }
        [HttpPost]
        public ActionResult ekle(kategorimodel ekle)
        {
            //view oluştururken edit olanı seçiyoruz
            DynamicParameters param = new DynamicParameters();
            param.Add("@kategoriid", ekle.kategoriid);
            param.Add("@kategoriad", ekle.kategoriad);
            DP.ExecuteWithoutReturn("kategoriekle", param);
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("kategoriid", id);
            DP.ExecuteWithoutReturn("kategorisilno", param);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvcdapper/aspnetmvcdapper/Views/kategori/Index.cshtml
@model IEnumerable<aspnetmvcdapper.Models.kategorimodel>

@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

<p>
    @*@Html.ActionLink("Kategori Ekle", "ekle")*@ <!--link şeklinde -->
    <button type="button" class="btn btn-info" onclick="location.href = '@Url.Action("ekle","kategori")'">Kategori Ekle</button><!--buton şeklinde -->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.kategoriad)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.kategoriad)
            </td>
            <td>
                @*@Html.ActionLink("Düzenle", "ekle", new { id = item.kategoriid })*@  <!--link şeklinde-->
                @*@Html.ActionLink("Sil", "Delete", new { id = item.kategoriid })*@ <!--link şeklinde-->
                <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("ekle","kategori",new { id = item.kategoriid })'">Düzenle</button>
                @*<button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("ekle","kategori", new { id = item.kategoriid }))'">Sil</button>*@ @*direk uyarı vermeden siler ve ındex sayfasına yönlendirir*@
                @Html.ActionLink("Sil", "Delete", new { id = item.kategoriid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İsteğinizden Emin Misiniz?')" }) @*1.parametre adı butonda gözükecek ad,2.parametre gideceği yer*@
            </td>         
        </tr>
    }

</table>

aspnetmvcdapper/aspnetmvcdapper/Views/kategori/ekle.cshtml
@model aspnetmvcdapper.Models.kategorimodel
@{ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; }  <!--_mainlayout adında shared içine view oluşturdum. burayada urlsini ekledim-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Kategori Ekle</h4>
    <hr />
    @Html.ValidationSummary(true) @*//ekledik, giden verilerin kontrolünü sağlar*@
    @Html.HiddenFor(model => model.kategoriid) @*//ekledik, id yi getirir*@
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.kategoriad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.kategoriad, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = 50 } }) @*required ve maxlength kısıtlamaları getirildi *@
            @Html.ValidationMessageFor(model => model.kategoriad, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />

            @*@Html.ActionLink("Geri Dön", "Index")*@ @*bu da çalışır ama buton özelliği vermek için aşağıdaki gibi yazılır*@
            <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Index","kategori")'">Geri Dön</button>
        </div>

    </div>
</div>
}

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@
<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>